#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: ../../heat-common/tasks/_set_directories.yml
  vars:
    install_package_result: "{{ ardana_notify_heat_engine_install_result }}"

- include: ../../heat-common/tasks/configure.yml

- include: ../../heat-common/tasks/_write_conf.yml
  src: "../../heat-engine/templates/engine.conf.j2"
  dest: "{{ heat_service_conf_dir }}/engine.conf"

- name: heat-engine | configure | notify on engine.conf change
  command: /bin/true
  register: ardana_notify_heat_engine_restart_required
  when: write_conf_result.changed

- name: heat-engine | configure | Create engine-logging.conf
  become: yes
  template:
    src: "engine-logging.conf.j2"
    dest: "{{ heat_service_conf_dir }}/engine-logging.conf"
    owner: "{{ heat_system_user }}"
    group: "{{ heat_system_group }}"
    mode: "0400"
  register: ardana_notify_heat_engine_restart_required

- name: heat-engine | configure | Copy files to config dir
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ heat_service_conf_dir }}"
    owner: "{{ heat_system_user }}"
    group: "{{ heat_system_group }}"
    mode: 0640
  with_items:
    - templates
  register: ardana_notify_heat_engine_restart_required

- name: heat-engine | configure | Template environment.d default.yaml
  become: yes
  template:
    src: "environment.d/default.yaml"
    dest: "{{ heat_environment_dir }}/default.yaml"
    owner: "{{ heat_system_user }}"
    group: "{{ heat_system_group }}"
    mode: 0600
  register: ardana_notify_heat_engine_restart_required

- name: heat-engine | configure | touch engine log files
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ heat_system_user }}"
    group: "{{ heat_log_group }}"
    mode: 0640
    state: touch
  with_items:
    - "{{ heat_log_location }}/heat-engine-json.log"
    - "{{ heat_log_location }}/heat-engine.log"
