#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: heat-caasp | install | install caasp-openstack-heat-templates package
  become: yes
  zypper:
    name: caasp-openstack-heat-templates
    state: present

- name: heat-caasp | install | check if caasp image exists in glance
  shell: |
      source {{ ardana_service_osrc_file }}
      openstack image show "{{ caasp_image_name }}"
  register: caasp_image_exists_result
  args:
    executable: /bin/bash
  ignore_errors: True

- name: heat-caasp | install | download caasp openstack qcow image to tmp
  get_url:
    url: "{{ caasp_image_url }}"
    dest: "{{ caasp_image_tmp_path }}"
    mode: 0600
  register: _download_caasp_image_result
  until: _download_caasp_image_result | success
  retries: 5
  delay: 2
  when: caasp_image_exists_result.rc > 0

- name: heat-caasp | install | upload caasp openstack qcow image to glance
  shell: |
    source {{ ardana_service_osrc_file }}
    openstack image create --public --disk-format qcow2 \
    --container-format bare \
    --file "{{ caasp_image_tmp_path }}" "{{ caasp_image_name }}"
  args:
    executable: /bin/bash
  when: caasp_image_exists_result.rc > 0

- name: heat-caasp | install | delete caasp openstack qcow image from tmp
  file:
    state: absent
    path: "{{ caasp_image_tmp_path }}"
  when: caasp_image_exists_result.rc > 0

- name: heat-caasp | install | check if caasp stack exists
  shell: |
      source {{ ardana_service_osrc_file }}
      openstack stack show "{{ caasp_stack_name }}"
  register: caasp_stack_exists_result
  args:
    executable: /bin/bash
  ignore_errors: True

- name: heat-caasp | install | create  caasp stack
  shell: |
      source {{ ardana_service_osrc_file }}
      openstack stack create --wait --timeout 120 \
      --template "{{ caasp_stack_yaml_file }}" \
      --environment "{{ caasp_stack_env_yaml_file }}"  \
      --parameter image="{{ caasp_image_name }}" "{{ caasp_stack_name }}"
  args:
    executable: /bin/bash
    chdir: "{{ caasp_stack_yaml_dir }}"
  when: caasp_stack_exists_result.rc > 0

- name: heat-caasp | install | get  caasp stack status
  shell: |
      source {{ ardana_service_osrc_file }}
      openstack stack show "{{ caasp_stack_name }}" \
      | grep -w stack_status | awk '{print $4}'
  args:
    executable: /bin/bash
  register: create_caasp_stack_result
  when: caasp_stack_exists_result.rc > 0

- name: heat-caasp | install | check  caasp stack status
  fail:
    msg: "Failed to create stack: {{ caasp_stack_exists_result.stdout }}"
  when:
    - caasp_stack_exists_result.rc > 0
    - create_caasp_stack_result.stdout != 'CREATE_COMPLETE'
